version: "3.3"

services:
  app:
    build: .
    depends_on:
      - banner_db
      - banner_cache
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    environment:
      REDIS_URL: banner_cache:6379
      DB_HOST: banner_db
      DB_PORT: 5432
    command: go run cmd/main.go

  banner_db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: banner_db
      POSTGRES_PASSWORD: banner_db
    ports:
      - "5434:5432"
  
  banner_cache:
    image: redis:alpine
    ports:
      - "6379:6379"