DROP TABLE IF EXISTS bannners CASCADE;
DROP TABLE IF EXISTS bannner_tag CASCADE;
DROP TABLE IF EXISTS banner_feature CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;